build system fixes

diff --git a/cli/Makefile b/cli/Makefile
--- a/cli/Makefile
+++ b/cli/Makefile
@@ -17,7 +17,7 @@ default: .release
 
 .release: listenkey$(EXE) sendkey$(EXE)
 	touch .release
-	@echo === Finished building listenkey$(EXE) and sendkey$(EXE) version $(VERSION)
+	@echo ━━━┫ Finished building listenkey$(EXE) and sendkey$(EXE) version $(VERSION)
 
 clean:
 	rm -rf listenkey sendkey *.exe .dep-* .version .release
@@ -39,17 +39,19 @@ sendkey: .dep-gcc *sendkey*.[ch] json-str.c common*.h .version jsonsl/jsonsl.*
 	echo '$(VERSION)' > .version
 
 .dep-mingw64:
-	@if which i686-w64-mingw32-gcc; then echo found mingw64 compiler; touch $@; else \
-		echo Missing Mingw-W64.; \
-		echo On Cygwin, install package mingw64-i686-gcc-core.; \
-		echo On Debian, install package gcc-mingw-w64-i686.; \
+	@if ! which i686-w64-mingw32-gcc; then \
+		echo '━━━┓ Missing Mingw-W64.'; \
+		echo '   ┃ On Cygwin, install package mingw64-i686-gcc-core'; \
+		echo '━━━┛ On Debian, install package gcc-mingw-w64-i686'; \
 		false; fi
+	touch $@
 
 .dep-gcc:
-	@if which gcc; then echo found gcc compiler; touch $@; else \
-		echo Missing GCC.; \
-		echo On Cygwin: install package gcc-core.; \
-		echo On Debian: apt-get update && apt-get install build-essential; \
+	@if ! which gcc; then \
+		echo '━━━┓ Missing GCC.'; \
+		echo '   ┃ On Cygwin: install package gcc-core'; \
+		echo '━━━┛ On Debian: apt-get update && apt-get install build-essential'; \
 		false; fi
+	touch $@
 
 .PHONY: default clean
diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -13,7 +13,7 @@ default: .release
 
 .release: $(MANPAGES) $(MANPAGES:=.html) $(MANPAGES:=.pdf)
 	touch .release
-	@echo === Finished building documentation for keyboa $(VERSION)
+	@echo ━━━┫ Finished building documentation for keyboa $(VERSION)
 
 man: $MANPAGES
 
@@ -22,7 +22,7 @@ html: $(MANPAGES:=.html)
 pdf: $(MANPAGES:=.pdf)
 
 clean:
-	rm -rf *.[15] *.[15].html *.[15].pdf .dep-* .version .release
+	rm -rf *.[15]* .dep-* .version .release
 
 %.1 %.5: %.scd .dep-scdoc .version
 	$(if $(findstring UNKNOWN,$(VERSION)),$(error Could not determine VERSION. Provide it manually or install git))
@@ -32,7 +32,7 @@ clean:
 	$(if $(findstring UNKNOWN,$(VERSION)),$(error Could not determine VERSION. Provide it manually or install git))
 	./gen $@ html $< "$(VERSION)"
 
-%.1.pdf %.5.pdf: %.scd .dep-pandoc .version
+%.1.pdf %.5.pdf: %.scd .dep-pandoc .dep-pdflatex .version
 	$(if $(findstring UNKNOWN,$(VERSION)),$(error Could not determine VERSION. Provide it manually or install git))
 	./gen $@ pdf $< "$(VERSION)"
 
@@ -41,16 +41,43 @@ clean:
 	echo '$(VERSION)' > .version
 
 .dep-scdoc:
-	@if which scdoc; then echo found scdoc compiler; touch $@; else \
-		echo Missing scdoc.; \
-		echo Install scdoc from https://git.sr.ht/~sircmpwn/scdoc; \
+	@if ! which scdoc; then \
+		echo '━━━┓ Missing scdoc.'; \
+		echo '━━━┛ Install scdoc from https://git.sr.ht/~sircmpwn/scdoc'; \
 		false; fi
+	touch $@
+
+.dep-pdflatex:
+	@if ! which pdflatex; then \
+		echo '━━━┓ Missing pdflatex.'; \
+		echo '   ┃ On Cygwin, install the following packages:'; \
+		echo '   ┃ - texlive-collection-latex'; \
+		echo '   ┃ - texlive-collection-fontsrecommended'; \
+		echo '   ┃ - texlive-collection-latexrecommended'; \
+		echo '━━━┛ On Debian: apt-get update && apt-get install texlive'; \
+		false; fi
+	@if ! kpsewhich xcolor.sty; then \
+		echo '━━━┓ Missing xcolor.sty.'; \
+		echo '   ┃ On Cygwin, install package texlive-collection-latexrecommended'; \
+		echo '━━━┛ On Debian: apt-get update && apt-get install texlive'; \
+		false; fi
+	@if ! kpsewhich lmodern.sty; then \
+		echo '━━━┓ Missing lmodern.sty.'; \
+		echo '   ┃ On Cygwin, install package texlive-collection-fontsrecommended'; \
+		echo '━━━┛ On Debian: apt-get update && apt-get install texlive'; \
+		false; fi
+	touch $@
 
 .dep-pandoc:
-	@if which pandoc; then echo found pandoc; touch $@; else \
-		echo Missing pandoc.; \
-		echo On Cygwin, install package todo; \
-		echo On Debian: apt-get update && apt-get install pandoc; \
+	@if ! which pandoc; then \
+		echo '━━━┓ Missing pandoc.'; \
+		echo '   ┃ On Cygwin: download pandoc-...-windows-i386.zip from'; \
+		echo '   ┃  https://github.com/jgm/pandoc/releases/ then:'; \
+		echo '   ┃   unzip pandoc*.zip'; \
+		echo '   ┃   chmod a+x pandoc*/pandoc.exe'; \
+		echo '   ┃   mv pandoc*/pandoc.exe /bin/'; \
+		echo '━━━┛ On Debian: apt-get update && apt-get install pandoc'; \
 		false; fi
+	touch $@
 
 .PHONY: default clean man html pdf
